---
- hosts: windows
  become: false
  gather_facts: false
  vars_files:
  - vault/passwords
  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks:
    - name: ping
      ansible.windows.win_ping:

    - name: Obtain information about a registry key using short form
      ansible.windows.win_reg_stat:
        path: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols
      register: current_version

    - name: debug
      debug:
        var: current_version
