---
- hosts: windows
  become: false
  gather_facts: false
  vars_files:
  - vault/passwords
  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks:
    - name: ping
      ansible.windows.win_ping:
