---
- hosts: windows
  become: false
  gather_facts: false
  vars_files:
  - vault/passwords
  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks:
    - name: Obtain information about a registry key using short form
      ansible.windows.win_reg_stat:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders
      register: current_version

    - name: debug
      debug:
        var: current_version

    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
          echo "Hello World"
      register: shell_out

    - name: debug
      debug:
        var: shell_out

